language: node_js
node_js: stable

install:
  - npm install
  - npm install hexo-cli -g

notifications:
  email:
    - chenzjnof118@163.com
  on_success: always
  on_failure: always

script:
  - hexo -v
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - ls -al
  - git init
  - git config --global user.name "NOF118"
  - git config --global user.email "chenzjnof118@163.com"
  - git add .
  - git commit -m "Auto deploy from Travis-CI "
  - git push --force  "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - master
env:
 global:
   - GH_REF: git@github.com:NOF118/myblog_publish.git


